### ISSUE TITLE
Connecting to a passworded instance using a constructor parameter

### ISSUE THREAD

**Issue by jmoriau** [stefanwille/crystal-redis#10]
Hello,

I read the documentation and browsed the code but I couldn't find any mention of how I should proceed to connect an instance with a password ?

(Other than that awesome work :+1: )

**Comment by stefanwille** [comment]
Thanks for the complement!

Please use the `Redis#auth` method:

https://github.com/stefanwille/crystal-redis/blob/master/src/redis/commands.cr#L80

http://redis.io/commands/AUTH

**Comment by jmoriau** [comment]
Ah didn't see that, I was looking for a way pass the password similar to ruby (when the Redis instance is created).

Thank you very much!

PS: Maybe it could be added as a constructor that would just call the current one and send the auth command ? It's not really important since it can be done by just sending the command after creation, but would be convenient :smile:

**Comment by stefanwille** [comment]
Yes, good idea, I will add it :smile:

**Comment by jmoriau** [comment]
Awesome :+1:
