### ISSUE TITLE
difference between blpop and brpop

### ISSUE THREAD

**Issue by sa-0001** [stefanwille/crystal-redis#111]
the following code works correctly for `brpop`, but raises an exception for `blpop`:

```
result = redis.brpop ["test_list"], 1
if result && result.size > 0 && result[0] == "test_list"
	pp result[1]
else
	puts "empty"
end
```

the above example correctly outputs the expected item.  however, change `brpop` to `blpop`, and the result is `Unhandled exception: Empty enumerable (Enumerable::EmptyError)`.

looking in the source code, i see that `blpop` and `brpop` are implemented slightly differently.  does this mean they need to be _used_ differently as well, or that there is a small inconsistency in the source?

**Comment by kostya** [comment]
this should be fixed in 2.7.0
