### ISSUE TITLE
Updating to crystal 1.0.0 ?

### ISSUE THREAD

**Issue by roduquen** [stefanwille/crystal-redis#114]
Hey, will redis be updated to crystal 1.0.0 ? Thanks

**Comment by kostya** [comment]
@stefanwille can you give repo access? i will update it

**Comment by stefanwille** [comment]
@kostya I will be happy to do so, thank you.

**Comment by stefanwille** [comment]
Done

**Comment by stefanwille** [comment]
I have also added @robacarp as maintainer to crystal-redis. He is also the maintainer of Mosquito. Please coordinate between the two of you.

**Comment by kostya** [comment]
pushed 2.7.0
