### ISSUE TITLE
Error: method Redis::TransactionApi#zadd must return (Int64 | String) but it is returning Redis::Future

### ISSUE THREAD

**Issue by CapnBerni** [stefanwille/crystal-redis#121]
Hello,

I'm doing some testing with crystal and sidekick.cr and it looks like I got an issue with redis (error in title).

I join the log trace here:
[trace.log](https://github.com/stefanwille/crystal-redis/files/7009866/trace.log)

Crystal 1.1.1
dependencies:
  redis:
    github: stefanwille/crystal-redis
    version: ~> 2.6
    
Reproduce:
clone repo: https://github.com/mperham/sidekiq.cr
shards install
crystal run examples/sidekiq.cr

**Comment by CapnBerni** [comment]
Issue opened on sidekick: https://github.com/mperham/sidekiq.cr/issues/111

**Comment by CapnBerni** [comment]
It works just adding the type to the method, I don't know yet what it implies but I let it there:
[commands.txt](https://github.com/stefanwille/crystal-redis/files/7009935/commands.txt)

**Comment by kostya** [comment]
if you lock crystal-redis version at 2.7.0 would it work?

**Comment by kostya** [comment]
i also pushed 2.8.2 which should fix it.

**Comment by CapnBerni** [comment]
It works, thanks a lot and have a nice day
