### ISSUE TITLE
Update to Crystal 0.16

### ISSUE THREAD

**Issue by raydf** [stefanwille/crystal-redis#17]
Hello:

I'm receiving this error:

```Can't infer the type of instance variable '@connection' of Redis::Strategy::SingleStatement```

Is there any planning on updating this library to the new version?

Thanks in advance,

raydf

**Comment by stefanwille** [comment]
Hello Rayner,

thanks for the issue. Yes, I am going to upgrade to Crystal 0.16. But I won't have the time to do it before my vacation. This means I will do this in 3 weeks.

**Comment by asterite** [comment]
Any help or questions you have with how to upgrade, let me know. If the error messages or the docs are not clear, I'll try my best to improve them :-)

**Comment by stefanwille** [comment]
@asterite Cool, thank you!

**Comment by raydf** [comment]
Thanks for the response @stefanwille. @asterite could you check the forked version i'm working (https://github.com/raydf/crystal-redis). There's a problem when i try to specify the abstract base for an instance variable:

```
instantiating 'Redis::PipelineApi#initialize(Redis::Strategy::Pipeline)'

in ./src/redis/pipeline_api.cr:19: instance variable '@strategy' of Redis::PipelineApi must be Redis::Strategy::SubscriptionLoop, not Redis::Strategy::Pipeline

  def initialize(@strategy : Redis::Strategy::Base)
```

Thanks,

raydf

**Comment by asterite** [comment]
The problem is that `Commands` has `@strategy = Redis::Strategy::SubscriptionLoop.new(@connection, subscription)` somewhere in the code, so the type is inferred to that type.

The solution is to add `@strategy : Strategy::Base` in the `Commands` module (let me know if that worked)

**Comment by stefanwille** [comment]
Seems to work. But I get more compile time errors about missing type declarations. I tried to go through them for a bit, but it's too many for today. This will have to wait until I am back.

**Comment by raydf** [comment]
@stefanwille i'll keep working in the forked version and if have success in compiling it all and passing specs i'll send PR to your project, thanks for the great work.

**Comment by stefanwille** [comment]
@raydf yes please, would be great.

**Comment by mperham** [comment]
@raydf Your fork gets further but the tests don't pass.  Notably pipeline and multi modes are still broken.

```
$ crystal spec/redis_spec.cr 
Error in ./spec/redis_spec.cr:835: instantiating 'Redis#pipelined()'

      results = redis.pipelined do |pipeline|
                      ^~~~~~~~~

in ./src/redis.cr:140: instantiating 'Redis::PipelineApi:Class#new(Redis::Strategy::Pipeline)'

    pipeline_api = Redis::PipelineApi.new(pipeline_strategy)
                                      ^~~

instantiating 'Redis::PipelineApi#initialize(Redis::Strategy::Pipeline)'

in ./src/redis/pipeline_api.cr:19: instance variable '@strategy' of Redis::PipelineApi must be Redis::Strategy::SubscriptionLoop, not Redis::Strategy::Pipeline

  def initialize(@strategy : Redis::Strategy::Base)
                 ^~~~~~~~~
```

**Comment by raydf** [comment]
Hello @mperham, i couldn't finish the work. I pushed my last commit to my fork. The version i'm using can execute simple redis commands without pipeline, but won't pass the tests. I believe we should wait for @stefanwille to make a complete update or help me with all the problems found.

**Comment by mperham** [comment]
I finished the work here https://github.com/stefanwille/crystal-redis/pull/18

**Comment by stefanwille** [comment]
PR #18 merged
