### ISSUE TITLE
autoreconnection

### ISSUE THREAD

**Issue by kostya** [stefanwille/crystal-redis#25]
would be nice if client have auto reconnection mode, because most production redis-servers have option `timeout 300`, and slow clients often failed with RedisError: Disconnected. And redis-rb have no this problem.

**Comment by kostya** [comment]
as workaround i using this hack: https://github.com/kostya/redis-reconnect

**Comment by stefanwille** [comment]
That's good feedback. I'll look into it.

**Comment by stefanwille** [comment]
Hi @emq, this came up 2 or 3 times recently. I guess it is best that I just integrate @kostya's redis-reconnect code for this, if he doesn't mind?

**Comment by kostya** [comment]
i think i will create pull request
