### ISSUE TITLE
raw method

### ISSUE THREAD

**Issue by maiha** [stefanwille/crystal-redis#29]
How do you like `raw` method that accepts Array(String) and invokes string_command stuff?

code: https://github.com/maiha/redis-cluster.cr/blob/master/src/ext/redis/raw.cr
usage: https://github.com/maiha/redis-cluster.cr/blob/master/spec/cluster/commands/raw_spec.cr

If you like this, I'll create a PR.
Of course, welcome to reject :)

Thanks.

**Comment by stefanwille** [comment]
Hi!

I am not sure what you are trying to achieve with the `raw` method. All the stuff in commands.cr (https://github.com/stefanwille/crystal-redis/blob/master/src/redis/commands.cr) is about making a nice interface with conveniently type casted return values for each command. All the method ultimately call `#command` on a strategy, such as in the SingleStatement strategy. I suspect that `#command` does what you want: it takes an array of Crystal values, sends them to Redis and handles the response in an appropriate way - by returning the response as Crystal value or by returning a Future. Maybe `#command` is all you need?

**Comment by maiha** [comment]
Yep, you're absolutely right! The `#command` is the very api I've been wanted!
Sorry for bothering you :)
Thank you very much!
