### ISSUE TITLE
sinter should accept an array of args

### ISSUE THREAD

**Issue by abduct** [stefanwille/crystal-redis#34]
The current implementation of `sinter` allows for multiple arguments via the splat operator which is good. 
```
    def sinter(*keys)
      string_array_command(concat(["SINTER"], keys))
    end

    private def concat(destination : Array(RedisValue), source)
      source.each { |value| destination << value.to_s }
      destination
   end
```

Although I believe there should also be an array overload which is in my opinion more useful. It could potentially be easily added like so:

```
    def sinter(keys : Array of String)
      string_array_command(concat(["SINTER"], keys))
    end
```

The reason behind this being more useful is because using tuples or single arguments may not be viable in all circumstances. For instance when collecting a group of keys **dynamically** during runtime. The current implementation is only really viable if you know which keys you are wanting to use at compile time or are provided them through a fixed API (ex: routing via kemal). But since there is no current way to convert an array to a compile time tuple and trying to assign an array to individual variables is a no go this would be a preferred feature. After all with dynamic data you never know if you will have 1 key or a few hundred.

This overload should likely be implemented on all redis functions that current use the splat for argument acceptance.

**Comment by stefanwille** [comment]
Somebody added this feature a while ago.
