### ISSUE TITLE
Subscribtion block not called.

### ISSUE THREAD

**Issue by ghost** [stefanwille/crystal-redis#39]
My Code:
```crystal
REDIS = Redis.new(database: 2)

REDIS.subscribe("test") do |on|
  puts typeof(on)

  on.message do |channel, message|
    puts message
  end
end
```

My output:
```

```

What my `redis-cli` receives:
```bash
127.0.0.1:6379> SUBSCRIBE test
Reading messages... (press Ctrl-C to quit)
1) "subscribe"
2) "test"
3) (integer) 1
1) "message"
2) "test"
3) "HELLOOOOOOSSS"
```

What I want: That the crystal-redis subscribtion gives me a message.

@stefanwille

**Comment by stefanwille** [comment]
HI Daniel, thanks for reporting. I will look into it.

**Comment by foi** [comment]
I have tried on crystal 0.22.0, crystal redis 1.8.0 and it's works.

**Comment by vladfaust** [comment]
@stefanwille you never looked into it. The one of the most major crystal libs is not maintained!

**Comment by stefanwille** [comment]
@vladfaust can you reproduce this issue?

**Comment by vladfaust** [comment]
I'm sorry, the bump wasn't related to this particular issue, I just wanted to call you see the other ones, 
 especially #4

**Comment by kostya** [comment]
i don't know what the issue is, subscription works for me in production very well.

**Comment by kostya** [comment]
not confirmed
