### ISSUE TITLE
 Does this support redis sentinel?

### ISSUE THREAD

**Issue by akashdeep-singh** [stefanwille/crystal-redis#41]
I'm working on an application that needs to suuport redis running with a sentinel cluster. I currently use node.js and https://github.com/ortoo/node-redis-sentinel solves my use case. I'm trying out crystal for a new module, and want to know if support for sentinel is on the cards?

**Comment by stefanwille** [comment]
@akashdeep-singh I am not working on redis sentinel support, although I think it would certainly be very interesting and educating. I am certainly open to PR's.

**Comment by akashdeep-singh** [comment]
@stefanwille Thanks for the response. I'm not good enough with crystal to start contributing yet, but I'll try and find time to make this work in the near future.
