### ISSUE TITLE
What is the recommended way to store small binary data using crystal-redis?

### ISSUE THREAD

**Issue by da99** [stefanwille/crystal-redis#47]
If I have binary data (eg MessagePack encoded data), shall I encode it to a string representation for Crystal-Redis?

**Comment by stefanwille** [comment]
Yes, I think so. I have no idea how to make a nice API using Slice(UInt8) for binary data.

**Comment by RX14** [comment]
No, this is wrong. Non-text data in a string is simply incorrect, and creating a `String` from `Bytes` causes a memory copy anyway. Encoding the binary data into a `String` using base64 for example to be valid crystal code takes even more of a performance hit. Please provide an adequate API for binary data.

**Comment by RX14** [comment]
I see you already use the binary-safe strings in redis. All you have to do is provide a `Bytes` overload of [this](https://github.com/stefanwille/crystal-redis/blob/82d6dda37b547f629c28157f3ad5a677594abb21/src/redis/connection.cr#L45) and relax relevent type restrictions to `String | Bytes`.
