### ISSUE TITLE
Execution gets stuck at the subscribe block

### ISSUE THREAD

**Issue by plainas** [stefanwille/crystal-redis#49]
I think this can be marked as a bug, because if it is a design choice, it's extremely limiting as we can only set up one subscriber and not to anything else.

The fact is that execution gets trapped in the subscribe block. The subscription works but the code stops there.

**Comment by stefanwille** [comment]
Are you using multiple threads?

**Comment by plainas** [comment]
Not that I am a ware of. I was trying to use this in a kemal app. Which didn't work because both kemal and crystal-redis pub sub required an event loop.

I commented out all code and left just the code from the pubsub example. I wen and red the docs that came with this module and it does appear that there is no way to subscribe without getting stuck in an event loop. Is that so?

**Comment by stefanwille** [comment]
I think now I get what you mean. You are calling subscribe and thread execution blocks, and you expected that it would continue instead. 

This is how Redis subscriptions are designed. A different behaviour would require a new thread / a spawn.
