### ISSUE TITLE
[suggestions] - please add support for disconnect / connection timeout

### ISSUE THREAD

**Issue by girng** [stefanwille/crystal-redis#53]
for example, if you do
```
puts "Connecting to Redis..."
begin
    redis = Redis.new
    puts "Connected to Redis: #{redis}"
rescue e
  abort "Failed to connect to Redis Server: #{e}"
end
```

the user will never get a raised error about failed to connect. in fact, the above code will block (unless u put it into a fiber)

my suggestion:
 - let us give a `connectiontimeout` to the parameter, and after xxx seconds if no connection, it will raise an error.
- if the master redis server dies, it should throw an error as well
- if the wrong password is given (or no password, but redis requires one), raise an error as well

ty for your time

**Comment by stefanwille** [comment]
Should not be too difficult: 

[TCPSocket.new(host, port, dns_timeout = nil, connect_timeout = nil)](
https://crystal-lang.org/api/0.21.0/TCPSocket.html#new%28host%2Cport%2Cdns_timeout%3Dnil%2Cconnect_timeout%3Dnil%29-class-method)

**Comment by girng** [comment]
@stefanwille i added
` tcpsocket = TCPSocket.new(host, port, false, 1)`

to line 16, in connection.cr. and the redis error "connection timeout" dose get raised. =]

i am very new to crystal, so please take my ideas/posts with grain of salt. i'm still learning the ropes, thanks you sir
