### ISSUE TITLE
Redis.mapping

### ISSUE THREAD

**Issue by Jens0512** [stefanwille/crystal-redis#56]
Something like `Redis.mapping` would be extremely convenient, and follows the convetion, eg. `JSON`, `YAML` and `DB` -`.mapping`.

I am quite new to redis, and would like to know whether this is realistic or not.

**Comment by kostya** [comment]
there is no any sense, you can use `JSON.mapping` or any other and `redis.set "bla", data.to_json`, `Data.from_json(redis.get("bla"))`

**Comment by Jens0512** [comment]
Yeah, alright, thanks!
