### ISSUE TITLE
integrate pool of connections with ysbaddaden/pool

### ISSUE THREAD

**Issue by kostya** [stefanwille/crystal-redis#60]
this is very needed in concurrent applications.

**Comment by stefanwille** [comment]
What type of integration do you have in mind? Connection pooling baked right in? Or would an example program do?

**Comment by kostya** [comment]
yes just baked in as redis-rb again.

**Comment by stefanwille** [comment]
So I guess the idea is a class `Redis::Pool`, where one can do this:

```
pool = Redis::Pool.new(host: ..., port: ..., pool_size: 250)
pool.redis do |conn|
     conn.set("mike", "rules") => "OK"
     conn.get("mike") => "rules"
end
```

**Comment by kostya** [comment]
if code have 100~ redis calls it problem to wrap every call with pool.redis

**Comment by stefanwille** [comment]
How would such a program checkout/checkin a connection? Explicitly, like so?

```
conn = pool.checkout
...
pool.checkin(conn)
```

**Comment by kostya** [comment]
not really imagine where and this can be used. for subscription only, but it can be hardcoded.

**Comment by stefanwille** [comment]
Sorry, I don't understand what you mean?

**Comment by stefanwille** [comment]
This is the API you had in mind?

https://github.com/stefanwille/crystal-redis/pull/61/files
