### ISSUE TITLE
lpush error when sending concurrent requests

### ISSUE THREAD

**Issue by parruda** [stefanwille/crystal-redis#70]
Hey guys,

I am using Kemal to receive requests on a specific endpoint and add a JSON to a queue to be consumed by workers using the [Reliable Queue Pattern](https://redis.io/commands/rpoplpush#pattern-reliable-queue).
Basically it does:

```
redis.lpush(queue_name, value)
```

Things start to fail when I send concurrent requests.

This works:

```
$ while true; do curl http://localhost:3000;done
```

Then I add a second one:

```
$ while true; do curl http://localhost:3000;done
```

That's when I start to see errors:

```
Exception: cast from String to Int64 failed, at /src/lib/redis/src/redis/command_execution/value_oriented.cr:12:9:12 (TypeCastError)
from src/lib/redis/src/redis/command_execution/value_oriented.cr:0:9 in 'integer_command'
```

What could be causing it?

**Comment by maiha** [comment]
Hi @parruda !

This library is not **thread-safe**. So you must handle connections by yourself.
The choices are as follows.

- a) wrap connections with  **connection pool** library like https://github.com/ysbaddaden/pool
- b) use thread-safe one like https://github.com/kostya/redisoid

Best regards,

**Comment by kostya** [comment]
use pooled_client: https://github.com/stefanwille/crystal-redis#connection-pooling

**Comment by stefanwille** [comment]
`Redis` objects are not thread safe. Please use @kostya's solution: `Redis::PooledClient`, as in @kostya's link.

**Comment by parruda** [comment]
Using the polled client works. Thanks guys!
