### ISSUE TITLE
cast from Int64 to (String | Nil) failed

### ISSUE THREAD

**Issue by codenoid** [stefanwille/crystal-redis#73]
```
cast from Int64 to (String | Nil) failed, at /var/app/MyApp/lib/redis/src/redis/command_execution/value_oriented.cr:39:9:39
```

**Comment by codenoid** [comment]
that's the problem

**Comment by stefanwille** [comment]
@codenoid please can you tell me how to reproduce the issue?

**Comment by codenoid** [comment]
idk, too many code in my project

**Comment by proyb6** [comment]
@codenoid Kindly write a small test at least, your previous issue in Crystal repo were closed for the same reason.

**Comment by codenoid** [comment]
![Joe](https://i.postimg.cc/yx8B2d05/99915.jpg)

**Comment by kostya** [comment]
i saw similar errors in another issues, and all this errors turns out was just concurrency errors, are you environment use concurrency?
