### ISSUE TITLE
crystal-redis leaks memory?

### ISSUE THREAD

**Issue by saturn-network** [stefanwille/crystal-redis#79]
Perhaps because of https://github.com/ysbaddaden/pool/issues/2

Symptoms: when using crystal-redis inside amber framework with pooledconnection to cache responses, heroku dynos run out of memory (I presume due to request buffer filling up) and no requests end up getting served, the get stuck on `redis.get`.

Does anybody have a success story using crystal-redis with amber framework or in production for web services in general?

**Comment by stefanwille** [comment]
Do you have repo that I can use to reproduce the issue?

**Comment by kostya** [comment]
there is no failed instances in pool, all connection reestablished when needed

**Comment by saturn-network** [comment]
@stefanwille unffortunately not at the moment. I shall do my best to come up with a minimal reproducible example and push that as a repo.

@kostya that may well be. Still, in practice what I have observed is that the instance grew its mem usage and died under load, and this only happens when we're using redis caching.

**Comment by stefanwille** [comment]
@saturn-network that minimal reproducible example would be very helpful

**Comment by saturn-network** [comment]
I can imagine :) Do you want to close the issue for now and have me reopen it when it's done, or do you want to keep it open?

**Comment by stefanwille** [comment]
Please leave this issue open for now.

**Comment by saturn-network** [comment]
Will open a new issue to track this with the writeup guiding through how the project is initialized, where redis comes into play, and we can discuss how to properly stress test the server and detect where the issues might be happening.

Perhaps the issue is with a specific amber version, or wrong usage of the language, or poorly configured GC
