### ISSUE TITLE
Bug when getting a value over 8K in length

### ISSUE THREAD

**Issue by edorrington** [stefanwille/crystal-redis#8]
Hi,

I'm running into an issue where if I try to do a GET on a key whose value is over 8K, I'm not getting the full value back, and the library is throwing an exception on the next command issued.

What appears to be happening is, in connection.cr, on line 91, you're reading from the socket into a slice, but not ensuring that the return value from the read (the # of bytes actually read), is equal to the amount requested. In the standard library IO::Buffered implementation of read (which TCPSocket uses), on line 161, if the slice to be read into has a size that's greater than IO::Buffered's BUFFER_SIZE (which is 8K), then it does an unbuffered read directly into the slice. So I'm assuming that it's just getting a partial read from the socket, leaving the rest of the value waiting on the socket for the next read, which gets erroneously read the next time a command is issued.

**Comment by stefanwille** [comment]
Hi Edward,

thanks for reporting! I will look into it.

**Comment by asterite** [comment]
You can use [IO#read_fully(slice)](http://crystal-lang.org/api/IO.html#read_fully%28slice%3ASlice%28UInt8%29%29-instance-method) for this and it'll probably be fixed. Also make sure to use it in other places of the protocol if you expect the IO to have exactly that amount of bytes.

Also, to improve performance, you can do:

```crystal
bulk_string = String.new(length) do |buffer|
  @socket.read_fully(Slice.new(buffer, length))
  {length, 0}
end
```

That avoids a double allocation (one with Slice.new, another with String.new) and just allocates a String. Check [String#new](http://crystal-lang.org/api/String.html#new%28capacity%3AInt%2C%26block%29-class-method).

**Comment by stefanwille** [comment]
@asterite cool, done! Works great!

@edorrington it's fixed, please try :smile:

**Comment by edorrington** [comment]
Thanks for the quick response! When I test the latest version in a simple app that just does as many gets as possible, it works fine for any size. But my actual use case is as a cache to store rendered ECR templates. When I am running it as part of a web app, and load test using wrk, I'm still getting a lot of errors whenever the value is greater than about 8k. I'll keep poking around to see if I can narrow it further.

I've created a minimal gist that shows the issue [here](https://gist.github.com/edorrington/0d9cbe979cb43669ba6f).

Thanks!

**Comment by stefanwille** [comment]
I simplified your gist a bit:

```Crystal
require "redis"
require "http/server"

KEY = "the-key"

R = Redis.new

result = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890" * 140
result = ",.-" + result
R.set(KEY, result)

server = HTTP::Server.new(8123) do |req|
           result = R.get(KEY)
           HTTP::Response.ok "text/html", result
         end

puts "Listening on http://0.0.0.0:8123"
server.listen
```

It shows the error:

```
Unhandled exception:
RedisError: Cannot parse response with type 5: "67890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890" (Redis::Error)
[4429016354] *CallStack::unwind:Array(Pointer(Void)) +82
[4429016257] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4429016216] *CallStack::new:CallStack +40
[4429053617] *Exception@Exception#initialize<Redis::Error, String>:CallStack +33
[4429053556] *Redis::Error#initialize<Redis::Error, String>:CallStack +68
[4429053452] *Redis::Error::new<String>:Redis::Error +92
[4429064948] *Redis::Connection#receive<Redis::Connection>:(Nil | String | Int64 | Array(Redis::RedisValue)) +1140
[4429077410] *Redis::Strategy::SingleStatement#command<Redis::Strategy::SingleStatement, Array(String)>:(Nil | String | Int64 | Array(Redis::RedisValue)) +50
[4429062849] *Redis#command<Redis, Array(String)>:alias.Redis::RedisValue +33
[4429062749] *Redis@Redis::CommandExecution::ValueOriented#string_or_nil_command<Redis, Array(String)>:String? +29
[4429063048] *Redis@Redis::Commands#get<Redis, String>:String? +168
[4428995609] ~fun_literal_27 +41
[4429082082] *HTTP::Server#handle_client<HTTP::Server, TCPSocket+>:Nil +242
[4428996639] ~fun_literal_34 +31
[4429029044] *Fiber#run<Fiber>:Nil +212
[4428986441] ~fun_literal_4 +9
[4429580590] co_runner +43
```

It seems that Crystal-Redis reads too many bytes from the socket. 

The scary thing is that it only occurs with >= 2 HTTP connections in wrk. With 1 HTTP connection everything is fine.

```bash
wrk --threads=1 --connections=2 --duration=30s http://localhost:8123/
```

I hope I will have a new idea how to debug this.

**Comment by stefanwille** [comment]
The issue is still dependent on value size. At 4092 bytes it occurs, 4030 it doesn't.

**Comment by stefanwille** [comment]
In master I have added a fix for the exception message that makes it more useful.

**Comment by stefanwille** [comment]
I finally understood what is happening. The code shares one socket across multiple threads, and that can't work. Each thread must have it's own tcp connection to Redis.

I am surprised that I haven't recognized this earlier - it's probably because I spend my work day in nonthreaded Rails territory.

So, here is a version that is not very efficient but works flawlessly:

```crystal
require "redis"
require "http/server"

KEY = "the-key"

R = Redis.new

result = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890" * 140
result = ",.-" + result
R.set(KEY, result)

server = HTTP::Server.new(8123) do |req|
  redis = Redis.new
  result = redis.get(KEY)
  HTTP::Response.ok "text/html", result
end

puts "Listening on http://0.0.0.0:8123"
server.listen
```

A more efficient version would use a connection pool.

I will update the docs to say that a Redis object can't be shared across threads.

**Comment by asterite** [comment]
@stefanwille What do you mean "across multiple threads"? Or did you mean coroutines?

**Comment by stefanwille** [comment]
@asterite yes, I mean coroutines.
