### ISSUE TITLE
Casting Int64 into Array(RedisValue)

### ISSUE THREAD

**Issue by amedeiros** [stefanwille/crystal-redis#80]
When using commands `zrangebyscore` and `zremrangebyscore` its possible for the command to return an Int64 from redis. in `Redis::CommandExecution::ValueOriented#string_array_command` and `Redis::CommandExecution::ValueOriented#array_or_nil_command`. 

Yes I am in a multithreaded environment and yes I am using the `PooledClient` (saw the other ticket).

Making these changes stopped the exceptions. I can make a pull request if this is the appropriate fix thanks.

```ruby
def array_or_nil_command(request : Request) : Array(RedisValue)?
  response = command(request)

  if typeof(response) == Int64
    return Array(RedisValue).new
  end

  response.as(Array(RedisValue)?)
end
```

```ruby
def string_array_command(request : Request) : Array(RedisValue)
  response = command(request)
  if typeof(response) == Int64
    return Array(RedisValue).new
  end

  response.as(Array(RedisValue))
end
```

**Comment by amedeiros** [comment]
Also side note this could be completely because of the multi threading in my app.

**Comment by kostya** [comment]
this quite hack, i think this should not be the case. Should be some wrong usage, your env really threaded or just concurrent? what pool size?

**Comment by amedeiros** [comment]
A hack indeed. Well currently I spawn a few different fibers each one using the the same PooledClient instance with the default size of 5.

**Comment by amedeiros** [comment]
Closing this was my fault.

**Comment by kostya** [comment]
Actually, when you use same PooledClient between fibers, it should not raise this error even if pool small (can only be problem if you use threads). When connection busy, it wait or raise PoolTimeoutError error. So, i only can imagine some crazy combination of `multi` or `pipeline` with other commands in concurrent env.
