### ISSUE TITLE
Error resolving redis (~> 2.0.0, 2.1.0)

### ISSUE THREAD

**Issue by IMS-Global** [stefanwille/crystal-redis#81]
shard.yml
-----------------------
name: web_socket
version: 0.1.0

authors:
  - IMS-Global

crystal: 0.27.2

license: UNLICENSED

targets:
  web_socket:
    main: src/web_socket.cr

  amber:
    main: lib/amber/src/amber/cli.cr

dependencies:
  amber:
    github: amberframework/amber
    version: 0.27.0
    #branch: master

  granite:
    github: amberframework/granite
    version: ~> 0.15.0

  quartz_mailer:
    github: amberframework/quartz-mailer
    version: ~> 0.5.1

  jasper_helpers:
    github: amberframework/jasper-helpers
    version: ~> 0.2.1

  pg:
    github: will/crystal-pg
    version: ~> 0.15.0

  citrine-i18n:
    github: amberframework/citrine-i18n
    version: 0.3.2

  redis:
    github: stefanwille/crystal-redis
    version: ~> 2.1.1

  mosquito:
    github: robacarp/mosquito
    version: 0.2.1

development_dependencies:
  garnet_spec:
    github: amberframework/garnet-spec
    version: ~> 0.2.1

shards install
------------------------------------
Brennicks-MacBook-Air:WebSocket biosci$ shards install
Fetching https://github.com/amberframework/amber.git
Fetching https://github.com/amberframework/amber-router.git
Fetching https://github.com/mosop/cli.git
Fetching https://github.com/mosop/optarg.git
Fetching https://github.com/mosop/callback.git
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/elorest/compiled_license.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/TechMagister/liquid.cr.git
Fetching https://github.com/phoffer/inflector.cr.git
Fetching https://github.com/amberframework/micrate.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-mysql.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/stefanwille/crystal-redis.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/luckyframework/shell-table.cr.git
Fetching https://github.com/jeromegn/slang.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/mosop/teeplate.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/amberframework/granite.git
Fetching https://github.com/amberframework/quartz-mailer.git
Fetching https://github.com/arcage/crystal-email.git
Fetching https://github.com/amberframework/jasper-helpers.git
Fetching https://github.com/amberframework/citrine-i18n.git
Fetching https://github.com/TechMagister/i18n.cr.git
Error resolving redis (~> 2.0.0, ~> 2.1.0)

Fix
-------------------
version: 2.0.0

**Comment by stefanwille** [comment]
I am not sure what you mean?
